### ISSUE TITLE
how to compile that lol

### ISSUE THREAD

**Issue by zielony12** [mashed-potatoes/PotatoNV#71]
idk how do i compile it plz help xd

**Comment by newbit1** [comment]
I did it with the [Free Edition of Visual Studio](https://visualstudio.microsoft.com/downloads/).
After Downloading and Installing, I've just added the git repo to it, and build it.
Make sure git is in your path, otherwise you will get an error with "git submodule" from
the C# Project file [PotatoNV-next.csproj](https://github.com/mashed-potatoes/PotatoNV/blob/0de740364003d16c7e0520b9814f1565e8dc7e66/PotatoNV-next/PotatoNV-next.csproj#L206)

**Comment by zielony12** [comment]
> I did it with the [Free Edition of Visual Studio](https://visualstudio.microsoft.com/downloads/).
> After Downloading and Installing, I've just added the git repo to it, and build it.
> Make sure git is in your path, otherwise you will get an error with "git submodule" from
> the C# Project file [PotatoNV-next.csproj](https://github.com/mashed-potatoes/PotatoNV/blob/0de740364003d16c7e0520b9814f1565e8dc7e66/PotatoNV-next/PotatoNV-next.csproj#L206)

lol i use arch btw

**Comment by mashed-potatoes** [comment]
https://github.com/mashed-potatoes/PotatoNV-crossplatform
have fun.
